package com.anagrams.finder;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import org.junit.Assert;
import org.junit.Test;

public class AnagramTest {

	/**Compares Anagrams generated for a given word with the actuals generated by the program
	 * for file input.txt
	 * @throws IOException
	 */
	@Test
	public void test() throws IOException {
		AnagramFinder anagramFinder = new AnagramFinder();
		HashMap<String, ArrayList<String>> map= anagramFinder.findAnagrams("/input.txt");
		String[]expected= new String[]{"kinship","pinkish"};
		ArrayList<String> actual=map.get(anagramFinder.sortString("kinship"));
		Assert.assertArrayEquals(expected, actual.toArray());
		
	}
	
	/**
	 * Compares anagrams generated by the program for a word with the expected result for that word.
	 * Compares longestWord anagram set generated by the program with the expected result.
	 * Compares the mostWord anagram set generated by the program with the expected result.
	 * @throws IOException
	 */
	@Test
	public void test2() throws IOException {

		AnagramFinder anagramFinder = new AnagramFinder();
		HashMap<String, ArrayList<String>> map= anagramFinder.findAnagrams("/input2.txt");
		String[]expected= new String[]{"punctilio" ,"unpolitic"};
		ArrayList<String> actual=map.get(anagramFinder.sortString("punctilio"));
		Assert.assertArrayEquals(expected, actual.toArray());
		String longestWord = anagramFinder.getLongestWord();
		Assert.assertArrayEquals(expected, map.get(longestWord).toArray());
		String mostWords = anagramFinder.getMostWords();
		String[] expectedMostWords = new String[]{"paste", "pates", "peats", "septa", "spate", "tapes" ,"tepas"};
		actual=map.get(mostWords);
		Assert.assertArrayEquals(expectedMostWords, actual.toArray());
		
	}

}
